import ThemeRegistry from './ThemeRegistry'
import './globals.css'
import { Inter } from 'next/font/google'
import NextAuthProvider from './NextAuthProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props) {
  const { children } = props
  const session = await getServerSession()

  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
        </NextAuthProvider>
      </body>
    </html>
  )
}
